#!/bin/bash
UNAME=igk
PASS=Fahk6iej
HOST=spb-ts1.spb.tbricks.com
###UNAME=tbricksup
###PASS=tbricks
###HOST=10.88.3.148
#HOST=at-i7

PLUGINS='--plugin cliprdr'

PID_FILE="/home/igk/.var/run/xfreerdp.pid"

function get_workspace()
{
echo $(perl -e '
    use JSON;
    use Data::Dumper;
    use strict;
    my $cmd=`i3-msg -t get_workspaces`;
    my @ws = @{JSON->new->utf8->decode($cmd)};

    for my $itm (@ws) {
        next if $itm->{focused} != JSON::PP::true;
        my $w = $itm->{rect}->{width};
        my $h = $itm->{rect}->{height};
        print "${w}x${h}";
#       print "WIDTH=$w\nHEIGHT=$h\n";
#       print Dumper($itm);
    }
')
}

function start_xfreerdp
{
    xfreerdp /d:'' /u:$UNAME /p:$PASS "/size:$(get_workspace)" /clipboard:true /v:$HOST 2>&1 
}


while getopts ":h:" opt; do
    case $opt in
        h)
            HOST=$OPTARG
            echo "Use host=\"$HOST\""
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            ;;
    esac
done

shift $((OPTIND-1))

case "$1" in
    "stop")
        if [ -e "$PID_FILE" ]; then
            kill $(cat $PID_FILE)
            rm $PID_FILE
        else
            echo "Seems process doesn't started."
        fi
    ;;

    "echo")
        echo xfreerdp -d '' -u $UNAME -p $PASS -g $(get_workspace) $PLUGINS $HOST 
    ;;

    "start") 
        start_xfreerdp >~/.var/xfrerdp.log &
#        xfreerdp -d '' -u $UNAME -p $PASS -g $(get_workspace) $PLUGINS $HOST 2>&1 
        echo "$!" >$PID_FILE
    ;;
    
    "nohup")
        start_xfreerdp
    ;;

    "toggle")
        if [ -s $PID_FILE ]; then
            $0 stop
        else
            $0 start
        fi ;


    ;;

#    "verbose" )
#        VERBOSE=TRUE; $0 $@;
#       xfreerdp -d "" -u $UNAME -p $PASS -g 'workarea' $PLUGINS $HOST  
#    ;;
    "help"|"-h"|"")
        echo "USAGE $0 start|stop|toggle|nohup"
    ;;
esac
# vim: set filetype=sh
