#!/bin/bash

# Helper functions

fname()
{
    fullfile=$1
    filename=$(basename "$fullfile")
    echo "${filename%.*}"
}

fext()
{
    fullfile=$1
    filename=$(basename "$fullfile")
    echo "${filename##*.}"
}

convert()
{
    file=$1
    file_tmp=$2
    perl  -e '
        while(<>){
            s/","/"|"/g;
            s/(?<=\d),(?=\d)/./g;
            s/"([\d.]+)"/$1/g;
            print;
        }' <$file|
        iconv -f cp1251 -t utf-8 > $file_tmp
}

###########################################################

add_quotes()
{
    file=$1
    awk <$file '
    BEGIN {
        FS="|";
        OFS="|";
    }
    {
        if ( $6 == $8) {
            $11 = 1;
        } else {
            if ( $5 == 0 ) {
                $11 = 0;
            } else {
                $11 = $7/$5 
            }
        }
        print
    }
    ' | column -s\| -t
}

usage()
{
    echo "USAGE: $0 <input>"
}

main()
{
    if [ -z "$1" ]; then
        usage
        exit 0
    fi
    file=$1
    cfile=$(dirname $file)/$(fname $file).utf.$(fext $file)
    $(convert $file $cfile)
    add_quotes $cfile
}

main $*

# vim: ft=sh nu 
