#!/bin/bash

if [ "$1" == "--detache" ]; then
    detache="true"
    shift;
fi

session=`tmux -2 list-sessions -F "#{?session_attached,,#{session_id}}" |grep -o '$[0-9]\+' |head -1`

if [ ! -z "$detache" ]; then
    tmux -2 -q has-session && exec tmux -2 attach-session -d

elif [ ! -z "$session" ]; then
    exec tmux -2 attach-session -t "$session"

else
    exec tmux -2 new-session
fi
